### ISSUE TITLE
Error when building using maven

### ISSUE THREAD

**Issue by lrojas94** [pac4j/spark-pac4j-demo#3]
I get the following error when I try to run mvn compile exec:java:

 Failed to execute goal on project spark-pac4j-demo: Could not resolve dependencies for project org.pac4j.demo:spark-pac4j-demo:jar:1.1.0-SNAPSHOT: The following artifacts could not be resolved: com.nimbusds:nimbus-jose-jwt:jar:4.11, commons-io:commons-io:jar:2.4: Could not find artifact com.nimbusds:nimbus-jose-jwt:jar:4.11 -> [Help 1]

**Comment by leleuj** [comment]
Very strange. This artifact (`nimbus-jose-jwt`) is in the Maven central repository: http://repo1.maven.org/maven2/com/nimbusds/nimbus-jose-jwt/4.11/

**Comment by Pinnelot** [comment]
I'm getting the same error. Was anyone able to get it fixed?

**Comment by leleuj** [comment]
The artifact is definitely in the Maven central repository, though the definition via the `oauth2-oidc-sdk` dependency uses a range of versions. I guess it may cause troubles with Maven 2. Which version of Maven do you use?

**Comment by Pinnelot** [comment]
After importing it to IntelliJ IDEA the library was found and I was able to run it. Also, now I'm able to run the demo from the command line.

Both, the command lines and IntelliJs maven version is 3.0.5.

**Comment by l-rojas** [comment]
I'll be trying the same thing later today and will post the results hoping that will solve it for anyone else.

**Comment by leleuj** [comment]
I'm upgrading spark-pac4j to pac4j v1.9. I encountered the same problem and removing the Jfrog repository (in the pom.xml) solves the issue.

**Comment by hemant-yogi** [comment]
Then how we can solve it with jfrog...

**Comment by leleuj** [comment]
In any case, you need the Maven central repository.
