### ISSUE TITLE
Best way to unit test the application

### ISSUE THREAD

**Issue by MichaelBitard** [pac4j/spark-pac4j-demo#7]
I was wondering if there was a way to make unit/integration tests smooth with spark-pac4j.
For now the only solution I came with was to not call the before in my tests, hence disabling all the security, but it's really far from a prod-like environment.

**Comment by leleuj** [comment]
I'm not exactly sure of what you want to do, but I think the best way is certainly to control the clients used for authentication in the security configuration, depending on the environment you run the application. You could use a fake client with the appropriate behaviors for your tests.

Please use the mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users for such questions

**Comment by MichaelBitard** [comment]
Ok thanks
