### ISSUE TITLE
Logout doesn't work 

### ISSUE THREAD

**Issue by mizgeliko** [pac4j/spark-pac4j-demo#9]
I used basic auth link "http://localhost:8080/basicauth" and then went back and click local logout.
After that I was redirected to "http://localhost:8080/?forcepostlogouturl" with the header Authorization:Basic.
Went back to "http://localhost:8080/basicauth" and got no prompt but saw that the request is authenticated 
_profiles: [#CommonProfile# | id: pwd | attributes: {username=pwd} | roles: [] | permissions: [] | isRemembered: false | clientName: IndirectBasicAuthClient | linkedId: null |]_

**Comment by millross** [comment]
Your browser caches basic auth credentials, so I suggest you contact the team that maintain your browser. Not a bug in pac4j - it can't force a browser to forget your basic auth stuff, it can only log you out on the server

**Comment by millross** [comment]
https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by mizgeliko** [comment]
I want to note that browser cache was cleared after logout.. but anyway if I want to use you app and play with the demo first, I expect that basic features work well...

**Comment by mizgeliko** [comment]
.. apparently it is no the bug in pac4j, but what the benefits of this framework if it does wrap the standard behaviour without adding an extra value? 
Obviously I can solve this issue by myself as it is not a new one (see https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication) but it will be not a part of the job pac4j do for me and I wonder if I need it at all?

**Comment by millross** [comment]
pac4j does exactly what it's supposed to do as regards basic auth. It's supposed to do the server-side stuff, and it does that. It doesn't take responsibility for client-side stuff.
